### ISSUE TITLE
`userinfo` method does not handle cases where scope is just `openid`

### ISSUE THREAD

**Issue by kwajiehao** [opengovsg/sgid-client#12]
### Describe the bug
`sgid-client` does not handle cases where the client's scope is just `openid`. 

When a client's scope is just `openid`, the auth request is not associated with any data or enc key. Therefore, the response from the sgID user info endpoint will contain undefined `data` and `key` attributes. Because the `sgid-client` does not perform null or `isEmpty` checks on the `key` and `data` attributes, it attempts to import an empty key, resulting in an error.

The error message is also misleading, because `sgid-client` obscures the original error thrown by the `jose` function used to decrypt the private key.

### To Reproduce
1. Create and register a new sgID client with just the `openid` scope
2. Integrate with sgID using the SDK, following the instructions at https://docs.id.gov.sg/onboarding-guide/integrating-using-the-sdk 
3. When retrieving data from the user info endpoint, the library throws an error message `Unable to decrypt or import payload key`

### Expected behavior
`sgid-client` skips the decryption step if the `key` attribute does not exist and returns just the sub.

**Comment by pregnantboy** [comment]
Closed by #14
