### ISSUE TITLE
Change `redirectUri` to `redirectUris` during initializing of TypeScript SDK

### ISSUE THREAD

**Issue by raynerljm** [opengovsg/sgid-client#37]
The RP should be able to register multiple `redirect URIs` while initializing the SDK. However, currently, the SDK only accepts as single string for the `redirectUri` in the constructor
        

![Image](https://user-images.githubusercontent.com/63008910/233904214-365fe8e5-7abf-45e8-8adf-a99a13873ee7.png)

        
Furthermore, while initializing the `Client` from the `openid-client` library, it accepts an array of redirect URIs. To work around this, we wrap the single `redirectUri` we receive with an array to pass it in
        
![Image](https://user-images.githubusercontent.com/63008910/233904250-4298f69c-62a0-4661-9c88-6e84bf71c9ef.png)

        
This is not ideal as if the RP requires multiple redirect URIs, they have to instantiate multiple instances of `SgidClient` with the same client credentials. See [Wira’s PR](https://github.com/opengovsg/sgid-test-app/blob/feat/api-endpoints-for-mobile/lib/sgid-client.service.js) line 79 - 94 for an example

**Comment by kwajiehao** [comment]
Fixed in #46
