### ISSUE TITLE
Add examples into `sgid-client`

### ISSUE THREAD

**Issue by raynerljm** [opengovsg/sgid-client#40]
- Demo apps are helpful for developers to learn from example
- Reference to relevant [SDK Development Strategy Doc](https://www.notion.so/opengov/SDK-development-strategy-36320a866b4d462b964d2fcd8c173ba5?pvs=4)

**Comment by kwajiehao** [comment]
Closing this because it's completed. Check out https://github.com/opengovsg/sgid-client/tree/develop/examples and https://github.com/opengovsg/sgid-client-python/tree/develop/examples
