### ISSUE TITLE
Update SDK to reference `well-known` endpoint

### ISSUE THREAD

**Issue by raynerljm** [opengovsg/sgid-client#41]
Currently, the SDK is constructing its own values for the necessary endpoints

![Image](https://user-images.githubusercontent.com/63008910/236371527-21021079-f52b-405f-a7ff-5beca852b561.png)

Update the SDK to reference the [`well-known` endpoint ](https://api.id.gov.sg/.well-known/openid-configuration) according to the [OpenID Discovery RFC](https://openid.net/specs/openid-connect-discovery-1_0.html)

**Comment by kwajiehao** [comment]
From our offline discussion: 

Jie Hao: "if our SDK references the well-known endpoint, this means that our SDK will need to make an extra API call which adds more latency for the RP app. I'm not sure if this tradeoff (extra latency for correctness of OIDC endpoints) is worth it given that we control both the SDK and the API server"

**Comment by kwajiehao** [comment]
Closing this issue because there's no urgent need for us to use the well-known endpoint in our SDK as our team is small and develops all products involved
